<?php

namespace App\Models;

use CodeIgniter\Model;


class OrderModel extends Model
{

    protected $table      = 'orders';
    protected $primaryKey = 'id';



    protected $allowedFields = ['order_no', 'shipping_cost', 'subtotal', 'total','order_customer_id','order_agent_id','order_status','created','updated_at'];
    
    public function AutoGeneratedOrderId()
    {    $arr_ord=[];
        $builder = $this->db->table('orders');
        $builder->selectMax('id');
        $tem = $builder->get()->getRowArray();
        $count = $tem['id'];
        $count++;
        $prefix = '';
        $arr=[
            'order_id'=>"NHC".$prefix . str_pad($count, 4, '0', STR_PAD_LEFT),
             'id'=>$count
        ];
        return $arr;
        // return "NHC".$prefix . str_pad($count, 4, '0', STR_PAD_LEFT);
    }
    public function orderDetails($agent_id)
    {
        // $builder = $this->db->table('orders');
        // $builder->select('*');
        // $builder->join('existing_customers', 'existing_customers.customer_id = orders.order_customer_id ');
        // $builder->join('users', 'users.id= orders.order_agent_id');
        // $builder->where('order_agent_id',$agent_id);
        // $builder->orderBy('orders.updated_at', 'DESC');
        // $query = $builder->get()->getResult();
        // return $query;
        $builder = $this->db->table('orders o');
        $builder->select('o.*,u.id as agent_id,u.username as agent_name, e.id as customer_id,e.customer_id as customerCode,e.title,
        e.name,e.lname,e.address,e.add2,e.state,e.country,e.city,e.zip_code,e.email,e.phone');
        $builder->join('existing_customers e', 'e.customer_id = o.order_customer_id ');
        $builder->join('users u', 'u.id= o.order_agent_id');
        $builder->where('o.order_agent_id',$agent_id);
        $builder->orderBy('o.updated_at', 'ASC');
        $query = $builder->get()->getResult();
        return $query;
    }
    public function orderModelView($ord_id)
    {
        $builder =$this->db->table('orders o');
        $builder->select('o.*,u.id as agent_id,u.username as agent_name, e.id as customer_id,e.customer_id as customerCode,e.title,
        e.name,e.lname,e.address,e.add2,e.state,e.country,e.city,e.zip_code,e.email,e.phone');
        $builder->join('existing_customers e', 'e.customer_id = o.order_customer_id ');
        $builder->join('users u', 'u.id= o.order_agent_id');
        $builder->where('o.id',$ord_id);
        $builder->orderBy('o.updated_at', 'DESC');
        $query = $builder->get()->getResultArray();
        return $query;
    }
    
}